### ISSUE TITLE
Format not working with the short display

### ISSUE THREAD

**Issue by shannonhochkins** [tuplo/numberfmt#13]
nf(6500, "0.0a") -> 7k, I don't want this to automatically round up I want to display the decimals, and i can't see anythin relating to rounding in the docs unfortunately, is there a way to fix this? I'd rather it return 6.5k

**Comment by ruicsh** [comment]
hey @shannonhochkins, thanks for your message.

I can't reproduce it, I wrote this unit test and it's correct for node>14. 
https://github.com/tuplo/numberfmt/blob/main/src/bug-reports.test.ts#L21

Where are you running this code, in the browser? Which locale?
In the background, that `nf` call translates to this native JS

```js
const nf = new Intl.NumberFormat('en-GB', {
  compactDisplay: 'short',
  currency: undefined,
  currencyDisplay: 'symbol',
  currencySign: 'standard',
  maximumFractionDigits: 1,
  minimumFractionDigits: 1,
  minimumIntegerDigits: undefined,
  notation: 'compact',
  numberingSystem: 'latn',
  signDisplay: 'auto',
  style: 'decimal',
  useGrouping: false,
  unit: undefined,
  unitDisplay: 'short'
});
const n = nf.format(6_500);
console.log(n);
```

What does this code log on your platform?

**Comment by shannonhochkins** [comment]
Thankyou for the reply, I upgraded the package it must have been a bug in a previous version!
