### ISSUE TITLE
Unexpected result with 0.00[0]

### ISSUE THREAD

**Issue by BoBo-Git** [tuplo/numberfmt#7]
Hi, I found a small problem with number format. (Version 1.7.3)

![CleanShot 2022-06-06 at 10 06 06@2x](https://user-images.githubusercontent.com/32190184/172082889-f5e6de08-808e-4615-a6b5-095da2f2eaa7.png)

Use `0.00[0]` to format number `123.4`, I expect result `123.40`, but got result `123.4`.

I think in this `0.00[0]` format, you should complete the two decimals.

**Comment by ruicsh** [comment]
hi @BoBo-Git thanks for your bug report, released `v1.7.4` fixes the issue

**Comment by BoBo-Git** [comment]
> hi @BoBo-Git thanks for your bug report, released `v1.7.4` fixes the issue

Thanks! The problem is already solved.
