### ISSUE TITLE
some browser rangeError

### ISSUE THREAD

**Issue by choutuan** [tuplo/numberfmt#8]
使用vue3 + ts引入tuplo后部分谷歌浏览器会报如下错误

![image](https://user-images.githubusercontent.com/46235315/173482044-362ac60b-6663-435e-b28a-84b4046f4da4.png)

**Comment by ruicsh** [comment]
hi @choutuan thanks for your bug report, can you tell what were the inputs to `numberfmt` to cause that error?

**Comment by BoBo-Git** [comment]
> hi @choutuan thanks for your bug report, can you tell what were the inputs to `numberfmt` to cause that error?

Hi @ruicsh, I also encountered similar problem, it happened in a lower version of the browser. It will cause error log & error ui.

The main problem is in a lower version of the browser, the `narrowSymbol` is not support, it support by version 77+ in Chrome.

Is there any way to be compatible?

**Comment by ruicsh** [comment]
hi @BoBo-Git , thanks for clarifying the issue. I think the best solution for older browsers' compatibility is to use polyfills. I believe `numberfmt` should have no dependencies, only be a thin layer on top of the standard `Intl.NumberFormat` API present on all modern browsers and nodejs. Can you use a polyfill and see if the problem persists?

https://stackoverflow.com/a/67903160

**Comment by choutuan** [comment]
@ruicsh Thanks for the idea. My problem is solved.I do this by using this link [https://formatjs.io/docs/polyfills/intl-numberformat/](https://formatjs.io/docs/polyfills/intl-numberformat/)
